# Generated by Django 3.1.7 on 2021-04-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210426_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossgroup',
            options={'verbose_name': 'Группа для индивидуальных дисц', 'verbose_name_plural': 'Группы для индивидуальных дисц'},
        ),
    ]
