# Generated by Django 3.1.7 on 2021-04-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0015_auto_20210426_2147'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regparticipant',
            name='command',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comanda', to='digest.command', verbose_name='команда'),
            preserve_default=False,
        ),
    ]
