# Generated by Django 3.1.7 on 2021-04-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_category', '0005_delete_participantcategory'),
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='chip',
        ),
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participant_category', to='sports_category.category', verbose_name='разряд'),
        ),
        migrations.AddField(
            model_name='participant',
            name='vid_sporta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participant_vid_sporta', to='digest.vidsporta', verbose_name='вид спорта'),
        ),
    ]
