# Generated by Django 3.1.7 on 2021-04-26 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_auto_20210426_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='disciplina',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_kod_event', to='digest.kodevent', verbose_name='вид спорта'),
        ),
        migrations.AlterField(
            model_name='human',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human', to='digest.city', verbose_name='город(регион)'),
        ),
        migrations.AlterField(
            model_name='human',
            name='first_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='last_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default=None, max_length=1, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='user_human',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human', to=settings.AUTH_USER_MODEL, verbose_name='связь с User'),
        ),
    ]
