# Generated by Django 3.1.7 on 2021-04-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0011_auto_20210426_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
    ]
