# Generated by Django 3.1.7 on 2021-04-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_category', '0005_delete_participantcategory'),
        ('digest', '0013_auto_20210426_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название города(района)'),
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='команда'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_long',
            field=models.CharField(blank=True, help_text='полное название группы', max_length=70, unique=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_short',
            field=models.CharField(blank=True, help_text='короткое название группы', max_length=10, unique=True, verbose_name='возр гр'),
        ),
        migrations.AlterField(
            model_name='group',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='human',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human', to='digest.city', verbose_name='город(регион)'),
        ),
        migrations.AlterField(
            model_name='human',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='human',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='sex',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='kodevent',
            name='kod',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='kodevent',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='место проведения'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_category', to='sports_category.category', verbose_name='разряд'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='category',
            field=models.CharField(blank=True, choices=[('ССВК', 'Высшая категория (ССВК)'), ('СС1К', 'Первая категория (СС1К)'), ('СС2К', 'Вторая категория (СС2К)'), ('СС3К', 'Третья категория (СС3К)')], max_length=4, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='statusevent',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vidsporta',
            name='kod',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='vidsporta',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='вид спорта'),
        ),
    ]
