# Generated by Django 3.1.7 on 2021-04-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0014_auto_20210426_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_kod_event', to='digest.kodevent', verbose_name='дисциплина'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_human', to='digest.human', verbose_name='человек'),
        ),
    ]
