# Generated by Django 3.1.7 on 2021-04-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0015_auto_20210426_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='date_prisv',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присвоения'),
        ),
    ]
