# Generated by Django 3.1.7 on 2021-04-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0016_participant_date_prisv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Человека', 'verbose_name_plural': 'Люди'},
        ),
    ]
