# Generated by Django 3.1.7 on 2021-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия, Имя', max_length=50, verbose_name='Фамилия, Имя')),
                ('contact', models.CharField(help_text='email или телефон', max_length=15, verbose_name='email или телефон')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('category', models.CharField(choices=[('Записаться', 'Записаться к тренеру'), ('Спросить', 'Задать вопрос'), ('Другое', 'Другое')], max_length=15, verbose_name='категория')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_trainer', to='digest.trainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Сообщение тренеру',
                'verbose_name_plural': 'Сообщение тренерам',
            },
        ),
    ]
