# Generated by Django 3.1.7 on 2021-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='разряд')),
                ('short_name', models.CharField(max_length=4, unique=True, verbose_name='разряд')),
                ('ball', models.PositiveSmallIntegerField(verbose_name='стоимость разряда')),
            ],
            options={
                'verbose_name': 'разряд',
                'verbose_name_plural': 'разряды',
            },
        ),
        migrations.CreateModel(
            name='ParticipantCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcategory_category', to='sports_category.category', verbose_name='разряд')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcategory_human', to='digest.human', verbose_name='участник')),
                ('vid_sporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcategory_vid_sporta', to='digest.vidsporta', verbose_name='вид спорта')),
            ],
            options={
                'verbose_name': 'с разрядом',
                'verbose_name_plural': 'с разрядами',
            },
        ),
    ]
