# Generated by Django 3.1.7 on 2021-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='полное название', max_length=30, verbose_name='разряд'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.CharField(help_text='короткое название', max_length=4, unique=True, verbose_name='разряд'),
        ),
    ]
