# Generated by Django 3.1.7 on 2021-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_category', '0002_auto_20210425_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='полное название', max_length=35, verbose_name='разряд'),
        ),
    ]
