# Generated by Django 3.1.7 on 2021-04-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_category', '0004_auto_20210425_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipantCategory',
        ),
    ]
